### ISSUE TITLE
Try to remove max_glyphs restriction from label

### ISSUE THREAD

**Issue by FoamyGuy** [adafruit/Adafruit_CircuitPython_Display_Text#131]
Making an issue now so that we keep this in mind. I do think we'll want to hold off on making this change at least until there is a stable release made that includes the changes to Group though so it might be a little bit until we actually need to do anything further.

displayio.Group has been updated to allow it's size to be mutable so more things can be added, and there is no need to use the `max_size` any longer.

We will be able to change label.Label to make use of this and remove the `max_glyphs` restriction.

**Comment by tannewt** [comment]
Let's start moving things off max_size once 6.2.0 has been stable for a little while. We don't want to drop max_size with 6.1.x

**Comment by FoamyGuy** [comment]
I'm going to re-open this one for now with the intent to figure out if we can safely remove `max_glyphs` from label. If it turns out not to be possible we can close this back up.
