### ISSUE TITLE
Add error handling for misspelled kwargs in adafruit_display_text.label

### ISSUE THREAD

**Issue by bradanlane** [adafruit/Adafruit_CircuitPython_Display_Text#202]
The parameters for the `adafruit_display_text.label` are **anchor_point** and **anchored_position**. This is confusing and results in frequent user errors. The error is not caught by Python which is difficult for a user to debug.

I don't know if there is a generalized solution for catching this type of error.

A solution for this specific case would be to add `anchor_position` as a property and raise an error on it.

**Comment by bradanlane** [comment]
I may be using `kwargs` incorrectly.

What I am saying is the following mistake does not generate an error:

```
from adafruit_display_text import label

tile = label.Label(font, text=msg, color=RED, scale=1, anchor_point=(0.0,0.0), anchor_position=(0, offset))
```

The result of this code is that `anchor_position` is ignored - aka has no effect - and results in the tile being at the top of the screen.

**Comment by dhalbert** [comment]
We had a discussion about this in discord: unknown keyword args are being ignored. I suggested we really need to fix that.

**Comment by tannewt** [comment]
I think this extra `**kwargs` is causing this: https://github.com/adafruit/Adafruit_CircuitPython_Display_Text/blob/main/adafruit_display_text/__init__.py#L249 It gets anything that doesn't match and doesn't do anything with it.
I suspect removing it will fix this issue.
