### ISSUE TITLE
Not included in 20241116 bundle build ?

### ISSUE THREAD

**Issue by YachtMango** [adafruit/Adafruit_CircuitPython_Display_Text#215]
I've download the latest zip file ( adafruit-circuitpython-bundle-9.x-mpy-20241116) and can't see 'adafruit_display_text' lib.

**Comment by FoamyGuy** [comment]
I just downloaded the 20241116 bundle from https://circuitpython.org/libraries and I do see this library in it.

Here is a screenshot showing it. 
![image](https://github.com/user-attachments/assets/65c079bc-186b-409f-b6af-a6d0adeec7de)


I would say try downloading again and then double check. Ensure that the file explorer is not sorting by something unexpected causing them to appear in a different order.

**Comment by YachtMango** [comment]
Thanks @FoamyGuy, User error as I was looking / searching for a file not a directory !! 

Issue closed
