### ISSUE TITLE
this does not work on the pyportal rn!

### ISSUE THREAD

**Issue by TG-Techie** [adafruit/Adafruit_CircuitPython_Display_Text#3]
```
  File "pyportal.py", line 30, in <module>
ValueError: max_size must be >= 1
```

**Comment by tannewt** [comment]
Please be more descriptive. What file are you running? What version of the library? What version of CircuitPython?

**Comment by ladyada** [comment]
hiya @TG-Techie we're using it a lot - if you are still having a problem please post example code for reproducing the bug!
