### ISSUE TITLE
The latest version seems to have introduced a text shifting bug

### ISSUE THREAD

**Issue by makermelissa** [adafruit/Adafruit_CircuitPython_Display_Text#63]
I think this was introduced by #57. I think what is happening is that as the text is updated, it is being shifted.
See https://github.com/adafruit/Adafruit_Blinka_PyPortal/issues/11 for more details.

**Comment by FoamyGuy** [comment]
It should be fixed with #59. If you have a moment give that one a try.

**Comment by makermelissa** [comment]
I'll give it a try @FoamyGuy.

**Comment by makermelissa** [comment]
Fixed via #59.
