### ISSUE TITLE
When text width changes, artifacts are left...

### ISSUE THREAD

**Issue by makermelissa** [adafruit/Adafruit_CircuitPython_Display_Text#67]
I noticed this after it had been running hours. When the text shrinks after a text update due to a variable width font, artifacts are left over. Here's the open weather demo running on a PyPortal.

![IMG_2240](https://user-images.githubusercontent.com/2681417/87075349-0c7dfe80-c1d5-11ea-8eef-984c2ccb34f0.jpeg)

**Comment by kmatch98** [comment]
Strange.  Let me take a look tomorrow to see if I can replicate it with a simple program.

**Comment by makermelissa** [comment]
Fixed via #69.
